name: deploytos3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Buld Website
        run: npm run build
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Deploy to S3
        with:
          command: cp
          source: ./dist/
          destination: s3://hotelprojectbot21
          aws_access_key_id: ${{ secrets.AWS_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          flags: --recursive
