name: deploytos3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Buld Website
        run: npm run build
      - name: Deploy to S3
        uses: stcalica/s3-upload@0.0.1
        with:
          # Bucket Name
          bucket: hotelprojectbot21 
          # Package to upload S3
          package: ./dist/
          # AWS Secret Key
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
